### PR TITLE
Update

### PR DESCRIPTION
**Pull request by Justman10000**

### CODE REVIEW

**Comment by Justman10000** [comment]
@clarkwinkelmann

**Comment by clarkwinkelmann** [comment]
Thanks for your suggestions.

I am not planning to bundle any other language except for English in the Flamarkt extensions, so I recommend you contribute those translations to the official German language pack. I'm not sure if the Flamarkt extensions are listed on Weblate yet, maybe you will have to reach out to Rob about this. Since no release has been tagged yet, translations are likely to be modified and some keys might be renamed, so I would recommend to wait until a 0.1 version of Flamarkt is finalized before translating.

Regarding the English translation changes, I have that same concern about waiting for a finalized version. Right now the translations are intentionally not optimized and heavily duplicated, since keys and the pages that use them might still change before release.

To address duplicated keys, I'd like to use the official Flarum method using the `ref` namespace as described in the extension documentation https://docs.flarum.org/extend/i18n#reusing-translations . You may re-submit a PR using that format, but I can't guarantee I'll merge it.

Right now this project is still frozen until I get some other things sorted out with my clients.

Thanks for your understanding.

**Comment by Justman10000** [comment]
Shit, I forgot that Flarum works differently!

**Comment by Justman10000** [comment]
Shit, I forgot that it by Flarum works differently!

**Pull request closed without merging**
